name: med_parser
description: A new Flutter project.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  riverpod: ^2.6.1  
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  flutter_localizations: 
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  record: ^6.0.0
  sherpa_onnx: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/model/
    - assets/onboarding_graphic.svg